# Generated by Django 6.0.1 on 2026-01-27 10:04

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ssn', encrypted_model_fields.fields.EncryptedCharField()),
                ('bio', encrypted_model_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
